/**
 * Runs the checks and writes docs/TEST-REPORT.md.
 *
 * A committed report goes stale the moment anything changes, so the report
 * records exactly when and against what it was produced: date, git commit,
 * Node version, fixtures slot. CI regenerates it, and a diff in the report is a
 * diff in reality.
 *
 *   npm run report             # local suites only (fixtures required)
 *   npm run report -- --live   # also the read-only mainnet suites
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, existsSync, readFileSync } from 'node:fs';

const WITH_LIVE = process.argv.includes('--live');

/** Strips anything that could carry a credential out of captured output. */
function redact(s: string): string {
  return s
    .replace(/(api[-_]?key=)[^&\s"']+/gi, '$1***')
    .replace(/(token=)[^&\s"']+/gi, '$1***')
    .replace(/https:\/\/[^\s"']*\/[0-9a-f]{16,}[^\s"']*/gi, 'https://<redacted-rpc>')
    .replace(/\bbigint: Failed to load bindings[^\n]*\n/g, '')
    .replace(/^npm notice[^\n]*\n/gm, '')
    .replace(/^\.env not found\. Continuing without it\.\n/gm, '');
}

/** `ok` is the exit code: node --test exits non-zero if any test failed. */
function run(cmd: string, args: string[]): { out: string; ok: boolean } {
  try {
    return { out: redact(execFileSync(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] })), ok: true };
  } catch (e) {
    const err = e as { stdout?: string; stderr?: string };
    return { out: redact(`${err.stdout ?? ''}${err.stderr ?? ''}`), ok: false };
  }
}

function git(args: string[]): string {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return 'n/a';
  }
}

/** Keeps the per-test lines and the counters, drops node:test boilerplate. */
function condense(out: string): string {
  return out
    .split('\n')
    .filter((l) => /^(✔|✖|ℹ (tests|pass|fail)|\s{4,}\S)/.test(l))
    .join('\n')
    .trimEnd();
}

function main() {
  if (!existsSync('fixtures/manifest.json')) {
    console.error('fixtures/ missing — run `npm run fixtures` first');
    process.exit(1);
  }
  const manifest = JSON.parse(readFileSync('fixtures/manifest.json', 'utf8'));

  console.log('typecheck…');
  const tsc = run('npx', ['tsc', '-p', 'tsconfig.json', '--noEmit']);
  console.log('local tests…');
  const local = run('npx', ['tsx', '--test', 'tests/refresh.test.ts', 'tests/flashloan.test.ts', 'tests/swap.test.ts']);
  const live = WITH_LIVE ? (console.log('live tests…'), run('npx', ['tsx', '--test', 'tests/live.readonly.test.ts'])) : null;
  const preflight = WITH_LIVE ? (console.log('preflight…'), run('npx', ['tsx', 'scripts/preflight.ts'])) : null;

  const pass = (r: { ok: boolean } | null) => (r === null ? 'not run (pass --live)' : r.ok ? 'passed' : 'FAILED');

  const md = `# Test report

Generated by \`npm run report\`. Do not edit by hand.

| | |
|---|---|
| Generated | ${new Date().toISOString()} |
| Commit | \`${git(['rev-parse', '--short', 'HEAD'])}\` ${git(['log', '-1', '--format=%s'])} |
| Node | ${process.version} |
| Fixtures captured at slot | ${manifest.slot} |

## Summary

| Suite | Result |
|---|---|
| typecheck | ${tsc.ok ? 'clean' : 'errors'} |
| local (LiteSVM, no network) | ${pass(local)} |
| live read-only (mainnet) | ${pass(live)} |

Per-test names and counts are in the blocks below.

## Local suites — real mainnet programs in LiteSVM

Programs loaded from \`fixtures/\`, executed locally with no network:
${Object.entries(manifest.programs as Record<string, { programId: string; bytes: number }>)
  .map(([n, p]) => `- **${n}** \`${p.programId}\` (${p.bytes.toLocaleString('en-US')} bytes)`)
  .join('\n')}

\`\`\`
${condense(local.out)}
\`\`\`
${
  live
    ? `
## Live read-only suites — real mainnet

No key, no signature, nothing submitted: the RPC transport rejects every method
that is not a read.

\`\`\`
${condense(live.out)}
\`\`\`
`
    : ''
}${
  preflight
    ? `
## Production readiness

\`\`\`
${preflight.out.trimEnd()}
\`\`\`
`
    : ''
}${
  tsc.ok
    ? ''
    : `
## Typecheck output

\`\`\`
${tsc.out.trimEnd()}
\`\`\`
`
}
`;

  writeFileSync('docs/TEST-REPORT.md', md);
  console.log('\nwrote docs/TEST-REPORT.md');
  process.exitCode = Number(!tsc.ok || !local.ok || live?.ok === false);
}

main();
