/**
 * Runs the checks and writes docs/TEST-REPORT.md.
 *
 * A committed report goes stale the moment anything changes, so the report
 * records exactly when and against what it was produced: date, git commit,
 * Node version, mainnet slot. CI regenerates it, and a diff in the report is a
 * diff in reality.
 *
 *   npm run report          # local suites only (fixtures required)
 *   npm run report -- --live   # also the read-only mainnet suites
 */
import { execFileSync, execSync } from 'node:child_process';
import { writeFileSync, existsSync, readFileSync } from 'node:fs';

const WITH_LIVE = process.argv.includes('--live');
const RPC = process.env.RPC ?? process.env.RPC_PRIMARY ?? 'https://api.mainnet-beta.solana.com';

/** Strips anything that could carry a credential out of captured output. */
function redact(s: string): string {
  return s
    .replace(/(api[-_]?key=)[^&\s"']+/gi, '$1***')
    .replace(/(token=)[^&\s"']+/gi, '$1***')
    .replace(/https:\/\/[^\s"']*\/[0-9a-f]{16,}[^\s"']*/gi, 'https://<redacted-rpc>')
    .replace(/\bbigint: Failed to load bindings[^\n]*\n/g, '')
    .replace(/^npm notice[^\n]*\n/gm, '');
}

function run(cmd: string, args: string[]): { out: string; ok: boolean; ms: number } {
  const t0 = Date.now();
  try {
    const out = execFileSync(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
    return { out: redact(out), ok: true, ms: Date.now() - t0 };
  } catch (e) {
    const err = e as { stdout?: string; stderr?: string };
    return { out: redact(`${err.stdout ?? ''}${err.stderr ?? ''}`), ok: false, ms: Date.now() - t0 };
  }
}

function git(args: string[]): string {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return 'n/a';
  }
}

async function currentSlot(): Promise<string> {
  try {
    const r = await fetch(RPC, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'getSlot', params: [] }),
    });
    const j = (await r.json()) as { result?: unknown };
    return String(j.result ?? 'n/a');
  } catch {
    return 'n/a';
  }
}

/** Pulls the `ℹ tests/pass/fail` summary lines out of a node:test run. */
function summary(out: string): { tests: number; pass: number; fail: number } | null {
  const num = (k: string) => {
    const m = out.match(new RegExp(`^\\s*[^\\n]*${k}\\s+(\\d+)\\s*$`, 'm'));
    return m ? Number(m[1]) : null;
  };
  const tests = num('tests'), pass = num('pass'), fail = num('fail');
  return tests === null || pass === null || fail === null ? null : { tests, pass, fail };
}

/** Keeps the per-test lines and the counters, drops node:test boilerplate. */
function condense(out: string): string {
  return out
    .split('\n')
    .filter((l) => /^(✔|✖|ℹ (tests|pass|fail)|\s{4,}\S)/.test(l))
    .join('\n')
    .trimEnd();
}

async function main() {
  if (!existsSync('fixtures/manifest.json')) {
    console.error('fixtures/ missing — run `npm run fixtures` first');
    process.exit(1);
  }
  const manifest = JSON.parse(readFileSync('fixtures/manifest.json', 'utf8'));

  console.log('typecheck…');
  const tsc = run('npx', ['tsc', '-p', 'tsconfig.json', '--noEmit']);
  console.log('local tests…');
  const local = run('npx', ['tsx', '--test', 'tests/refresh.test.ts', 'tests/flashloan.test.ts', 'tests/swap.test.ts']);
  const live = WITH_LIVE ? (console.log('live tests…'), run('npx', ['tsx', '--test', 'tests/live.readonly.test.ts'])) : null;
  const preflight = WITH_LIVE ? (console.log('preflight…'), run('npx', ['tsx', 'scripts/preflight.ts'])) : null;

  const slot = await currentSlot();
  const lsum = summary(local.out);
  const vsum = live ? summary(live.out) : null;

  const md = `# Test report

Generated by \`npm run report\`. Do not edit by hand.

| | |
|---|---|
| Generated | ${new Date().toISOString()} |
| Commit | \`${git(['rev-parse', '--short', 'HEAD'])}\` ${git(['log', '-1', '--format=%s'])} |
| Node | ${process.version} |
| Mainnet slot at run time | ${slot} |
| Fixtures captured at slot | ${manifest.slot} |

## Summary

| Suite | Result |
|---|---|
| typecheck | ${tsc.ok ? '✅ clean' : '❌ errors'} |
| local (LiteSVM, no network) | ${lsum ? `${lsum.pass}/${lsum.tests} passed${lsum.fail === 0 ? ' ✅' : ' ❌'}` : 'n/a ❌'} |
| live read-only (mainnet) | ${vsum ? `${vsum.pass}/${vsum.tests} passed${vsum.fail === 0 ? ' ✅' : ' ❌'}` : 'not run (pass --live)'} |

## Local suites — real mainnet programs in LiteSVM

Programs loaded from \`fixtures/\`, executed locally with no network:
${Object.entries(manifest.programs as Record<string, { programId: string; bytes: number }>)
  .map(([n, p]) => `- **${n}** \`${p.programId}\` (${p.bytes.toLocaleString('en-US')} bytes)`)
  .join('\n')}

\`\`\`
${condense(local.out)}
\`\`\`
${
  live
    ? `
## Live read-only suites — real mainnet

No key, no signature, nothing submitted: the RPC transport rejects every method
that is not a read.

\`\`\`
${condense(live.out)}
\`\`\`
`
    : ''
}${
  preflight
    ? `
## Production readiness

\`\`\`
${preflight.out.trimEnd()}
\`\`\`
`
    : ''
}${
  tsc.ok
    ? ''
    : `
## Typecheck output

\`\`\`
${tsc.out.trimEnd()}
\`\`\`
`
}
`;

  writeFileSync('docs/TEST-REPORT.md', md);
  console.log('\nwrote docs/TEST-REPORT.md');
  const failed = !tsc.ok || !local.ok || (live !== null && !live.ok);
  process.exitCode = failed ? 1 : 0;
}

void main();
